steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/medusa-repo/medusa-backend:latest', '-f', 'apps/backend/Dockerfile', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/medusa-repo/medusa-backend:latest']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/medusa-repo/medusa-backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8
